version: "3"
services:
  es:
    hostname: es
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0 #${STACK_VERSION}
    # env_file:
    #   - ../.env
    environment:
      - discovery.type=single-node
      - node.name=es
      - ELASTIC_PASSWORD=worksfine #${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
    ports:
      - 9200:9200
    expose:
      - 9200 #${ES_PORT}
    networks:
      - rxiv-rest
    healthcheck:
      # curl -u elastic:worksfine -k https://es:9200
      test: ["CMD-SHELL", "curl -s -k https://localhost:9200 | grep -q 'missing authentication credentials'"]

  app:
    build:
      context: ..
      dockerfile: containers/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - es
    networks:
      - rxiv-rest

networks:
  rxiv-rest:
    driver: bridge
